# We want to cache the vendor dir.
cache:
  # this expands to the branch, eg: 'master'
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/

before_script:
# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

# This package is PHP8-only.
test:php8.0:
  image: php:8.0-cli
  script:
  - php composer.phar dev:qa

